package VIEW;
import DAO.PessoaFisicaDAO;
import DAO.PessoaJuridicaDAO;
import DTO.PessoaFisicaDTO;
import DTO.PessoaJuridicaDTO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;import javax.swing.JCheckBox;

public class TelaLoginVIEW extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginVIEW
     */
    public TelaLoginVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCampoTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCampoSenha = new javax.swing.JPasswordField();
        botaoAcessar = new javax.swing.JButton();
        mostrarSenha = new javax.swing.JCheckBox();
        botaoCriarConta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jButton2.setText("jButton2");
        jButton2.setMaximumSize(new java.awt.Dimension(0, 0));
        jButton2.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Acesse sua conta");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CPF/CPNJ:");

        txtCampoTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCampoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoTextoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SENHA:");

        txtCampoSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoSenhaActionPerformed(evt);
            }
        });

        botaoAcessar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoAcessar.setForeground(new java.awt.Color(0, 0, 0));
        botaoAcessar.setText("Acessar");
        botaoAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcessarActionPerformed(evt);
            }
        });

        mostrarSenha.setBackground(new java.awt.Color(153, 153, 153));
        mostrarSenha.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mostrarSenha.setForeground(new java.awt.Color(0, 0, 0));
        mostrarSenha.setText("Mostrar a Senha");
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });

        botaoCriarConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCriarConta.setForeground(new java.awt.Color(0, 0, 0));
        botaoCriarConta.setText("Criar Conta");
        botaoCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarContaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("X");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mostrarSenha)
                                            .addComponent(jLabel1)
                                            .addComponent(txtCampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botaoAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(botaoCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54)))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarSenha)
                .addGap(28, 28, 28)
                .addComponent(botaoAcessar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCriarConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarContaActionPerformed
        DescisaoVIEW ds = new DescisaoVIEW();
        ds.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCriarContaActionPerformed

    private void botaoAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcessarActionPerformed
        try{
            String cpf, Senha;
            String cnpj, senha;
            /*
            Recebe os valores digitados nos campos de texto
            para Cpf e Senha da Pessoa Fisica, Cnpj e Senha
            da Pessoa Juridica
            */
            cpf = txtCampoTexto.getText();
            Senha = txtCampoSenha.getText();
            cnpj = txtCampoTexto.getText();
            senha = txtCampoSenha.getText();

            // Instanciando a classe PessoaFisicaDTO
            PessoaFisicaDTO cfdto = new PessoaFisicaDTO();
            /* O valor que está na váriavel cpf o sistema
            irá comparar com o que está no banco de dados,
            tanto o Cpf tanto a Senha
            */
            cfdto.setCpf(cpf);
            cfdto.setSenha(Senha);

            // Instanciando a classe PessoaFisicaDAO
            PessoaFisicaDAO cfdao =  new PessoaFisicaDAO();

            /* Usando o ResultSet assim ele consegue fazer a autenticação,
            e assim verificando se o cpf e a senha informados são os
            mesmo do banco de dados na tabela pessoa fisica
            */
            ResultSet rscfdao = cfdao.autenticacaoUsuario(cfdto);

            // Instanciando a classe PessoaJuridicaDTO
            PessoaJuridicaDTO cjdto = new PessoaJuridicaDTO();
            /*
            O valor que está na váriavel cnpj, o sistema irá
            comparar com o que está no banco de dados, tanto
            o Cnpj tando a Senha
            */
            cjdto.setCnpj(cnpj);
            cjdto.setSenha(senha);

            // Instanciando a classe PessoaJuridicaDAO
            PessoaJuridicaDAO cjdao = new PessoaJuridicaDAO();

            /* Usando o ResultSet assim ele consegue fazer a autenticação,
            e assim verificando se o cnpj e a senha informados são os
            mesmo do banco de dados na tabela pessoa juridica
            */
            ResultSet rscjdao =  cjdao.autenticacaoJuridica(cjdto);

            /*
            Verifica se a autenticação foi bem-sucedida para pessoa
            fisica ou juridica
            */
            if (rscfdao.next() || rscjdao.next()){
                TelaPrincipalVIEW telaPrincipal = new TelaPrincipalVIEW();
                telaPrincipal.setVisible(true);
                dispose(); // fecha a tela login
            }

            /*
            Cai aqui caso o cpf/cpnj e senha forem informados errados ou
            se caso não tiverem registrados
            */
            else{
                // enviar mensagem dizendo incorreto.
                JOptionPane.showMessageDialog(null, "Cpf e/ou Senha incorreto(s)!");
            }

            // Cai aqui se caso a conexão não for bem-sucedida
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "TelaLoginVIEW" + e);
        }
    }//GEN-LAST:event_botaoAcessarActionPerformed

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed

        if (mostrarSenha.isSelected()){
            /* se caso a caixa de seleção "mostrarSenha" estiver marcada
            exibe a senha em texto no campo password
            */
            txtCampoSenha.setEchoChar((char)0); // Exibe a Senha
        } else {
            /*
            // Caso contrário, oculta a senha com asteriscos
            (o comportamento padrão)
            */
            txtCampoSenha.setEchoChar('*'); // Oculta a senha com asteriscos
        }
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void txtCampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoSenhaActionPerformed

    }//GEN-LAST:event_txtCampoSenhaActionPerformed

    private void txtCampoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoTextoActionPerformed
    private void gravaInfo(){
        PessoaFisicaDTO objCfdto = new PessoaFisicaDTO();
        PessoaJuridicaDTO objCjdto = new PessoaJuridicaDTO();
        String txtCampo = txtCampoTexto.getText();
        objCfdto.setCpf(txtCampo);
        objCjdto.setCnpj(txtCampo);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAcessar;
    private javax.swing.JButton botaoCriarConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JPasswordField txtCampoSenha;
    private javax.swing.JTextField txtCampoTexto;
    // End of variables declaration//GEN-END:variables
}
